name: Build

on:
  pull_request: { }
  push: { branches: [ master ] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Checkout package repository
        uses: actions/checkout@v2
        with:
          lfs: true
          repository: aarthificial/reanimation
          token: ${{ secrets.ACCESS_TOKEN }}
          path: Packages/com.aarthificial.reanimation

      - name: Cache libraries
        uses: actions/cache@v1.1.0
        with:
          path: .tests/Library
          key: Library

      - name: Build project
        id: build
        uses: game-ci/unity-builder@v2.0-alpha-2
        with:
          unityVersion: 2020.2.0f1
          targetPlatform: StandaloneWindows

      - name: Save build
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build